# Generated by Django 6.0.3 on 2026-03-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies_app", "0002_movie_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="release_year",
            field=models.IntegerField(default=2026),
        ),
    ]
