# Generated by Django 6.0.3 on 2026-03-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies_app", "0003_alter_movie_release_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
