# Generated by Django 6.0.3 on 2026-03-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies_app", "0004_alter_movie_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="rental_price",
            field=models.DecimalField(decimal_places=2, default=1.95, max_digits=2),
        ),
    ]
