# Generated by Django 6.0.3 on 2026-03-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies_app", "0005_movie_rental_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="rental_price",
        ),
    ]
