# Generated by Django 6.0.3 on 2026-03-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies_app", "0007_movie_created_at_movie_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="rental_price",
            field=models.DecimalField(decimal_places=2, default=1.95, max_digits=5),
        ),
    ]
