# Generated by Django 6.0.3 on 2026-03-04 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies_app", "0008_movie_rental_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("special_power", models.CharField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to="movies_app.movie",
                    ),
                ),
            ],
        ),
    ]
