# Generated by Django 6.0.3 on 2026-03-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies_app", "0009_moviecharacter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name="movie",
            name="genre",
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(blank=True, to="movies_app.genre"),
        ),
    ]
