# Generated by Django 4.2.29 on 2026-03-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('main_character', models.CharField(max_length=300)),
                ('num_seasons', models.IntegerField()),
            ],
        ),
    ]
